version: 2

sources:
  - name: raw
    database: finpulse
    schema: raw
    description: Dados brutos do dataset BankChurners carregados no PostgreSQL.

    tables:
      - name: bank_churners
        description: Snapshot original de clientes de cartão de crédito e seu status de attrition.

        columns:
          - name: client_num
            description: Identificador único do cliente.
            tests:
              - not_null
              - unique

          - name: attrition_flag
            description: Situação observada do cliente.
            tests:
              - not_null
              - accepted_values:
                  values:
                    - Existing Customer
                    - Attrited Customer